# Generated by Django 4.2.2 on 2023-06-25 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faq', '0005_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(related_name='question_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
