# Generated by Django 4.2.2 on 2023-06-20 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_category_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 15, 42, 57, 832713, tzinfo=datetime.timezone.utc)),
        ),
    ]
