# Generated by Django 4.2.2 on 2023-06-21 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_tags_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 9, 29, 13, 91640, tzinfo=datetime.timezone.utc)),
        ),
    ]
