# Generated by Django 4.2.2 on 2023-06-22 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_body_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 6, 4, 18, 166645, tzinfo=datetime.timezone.utc)),
        ),
    ]
