# Generated by Django 4.2.2 on 2023-06-24 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 22, 25, 46, 438796, tzinfo=datetime.timezone.utc)),
        ),
    ]
