# Generated by Django 4.2.2 on 2023-06-24 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 23, 7, 37, 941646, tzinfo=datetime.timezone.utc)),
        ),
    ]
